name: ansible-lint

on: ["push", "pull_request"]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@master

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
