name: galaxy-upload

on: ["push"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repository
        uses: actions/checkout@master

      - name: galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
